#!/usr/bin/env bash
# GitHub Codespaces only: do not run this on a local workstation.
set -euo pipefail

if [[ "${CODESPACES:-}" != "true" && "${PIIK_PREVIEW_CI:-}" != "true" ]]; then
  echo "This preview launcher is for GitHub Codespaces only." >&2
  exit 1
fi

: "${CODESPACE_NAME:?CODESPACE_NAME must be provided by GitHub Codespaces}"
if [[ ! "$CODESPACE_NAME" =~ ^[a-zA-Z0-9][a-zA-Z0-9-]*$ ]]; then
  echo "Unexpected CODESPACE_NAME format" >&2
  exit 1
fi

port=8787
domain="${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-app.github.dev}"
if [[ ! "$domain" =~ ^[a-zA-Z0-9.-]+$ ]]; then
  echo "Unexpected Codespaces forwarding domain" >&2
  exit 1
fi
public_url="https://${CODESPACE_NAME}-${port}.${domain}"
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
binary="$root/build/piik-server"
data_dir="$root/build/codespaces"
pid_file="$data_dir/piik-server.pid"
log_file="$data_dir/piik-server.log"
password_file="$data_dir/host-password.txt"

if [[ ! -s "$binary" ]]; then
  echo "Piik server is missing; Codespaces build must finish first." >&2
  exit 1
fi

umask 077
mkdir -p "$data_dir"
if [[ -n "${PIIK_PREVIEW_SITE_PASSWORD:-}" ]]; then
  password="$PIIK_PREVIEW_SITE_PASSWORD"
else
  # Local untracked file, never committed or printed to Actions output.
  if [[ ! -s "$password_file" ]]; then
    node -e "process.stdout.write(require('node:crypto').randomBytes(18).toString('hex')+'\n')" > "$password_file"
  fi
  password="$(cat "$password_file")"
fi

if [[ -s "$pid_file" ]] && kill -0 "$(cat "$pid_file")" 2>/dev/null; then
  echo "Piik preview is already running at $public_url"
  exit 0
fi

# Do not propagate the Codespace's GITHUB_TOKEN or other secrets to Piik.
app_env=(
  "PATH=$PATH"
  "HOME=$HOME"
  "PIIK_ENV=development"
  "LISTEN_HOST=0.0.0.0"
  "PORT=$port"
  "PUBLIC_BASE_URL=$public_url"
  # GitHub Codespaces' HTTPS forwarding proxy may rewrite a same-origin
  # browser POST Origin to http://localhost:8787 before Piik receives it.
  # Explicitly permit only that loopback origin and the exact public preview
  # origin. Do not disable Piik's origin validation or add a wildcard.
  "ALLOWED_ORIGINS=$public_url,http://localhost:$port"
  "SITE_ACCESS_PASSWORD=$password"
  "ROOM_DATABASE_PATH=:memory:"
  "ROOM_EMPTY_TIMEOUT_SECONDS=3600"
  "MAX_VIEWERS_PER_ROOM=2"
  "STUN_URLS=${PIIK_PREVIEW_STUN_URLS:-stun:stun.l.google.com:19302}"
  "STUN_LISTEN_HOST=127.0.0.1"
  "SFU_ONLY=false"
  "NAT_PREDICTION_ENABLED=false"
)

(cd "$root" && env -i "${app_env[@]}" "$binary" --check-config)
(cd "$root" && nohup env -i "${app_env[@]}" "$binary" > "$log_file" 2>&1 < /dev/null & echo "$!" > "$pid_file")

for attempt in {1..40}; do
  if curl --silent --fail --max-time 2 "http://127.0.0.1:$port/healthz" | grep -q '"status":"ok"'; then
    echo "Piik preview is ready. Open forwarded port 8787 in the Codespaces PORTS tab."
    echo "HTTPS preview origin: $public_url"
    echo "Site-access password (if autogenerated) is in build/codespaces/host-password.txt."
    exit 0
  fi
  sleep 0.5
done

echo "Piik did not become healthy in the expected window." >&2
tail -n 30 "$log_file" >&2 || true
exit 1
